

name: Tests

on:
  push:
    branches:
  pull_request:
    branches:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Dependencies | Test
        run: |
          python setup.py sdist
          pip install dist/*
      - name: Unit Test | Test
        run: pytest -v tests